<?php
/**
 * HtmlApi
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * WebScraping.AI
 *
 * A client for https://webscraping.ai API. It provides Chrome JS rendering, rotating proxies and HTML parsing for web scraping.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\webscraping_ai;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * HtmlApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class HtmlApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index)
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getPage
     *
     * Get page HTML by URL (renders JS in Chrome and uses rotating proxies)
     *
     * @param  string $url URL of the page to get (required)
     * @param  string $selector CSS selector to get a part of the page (null by default, returns whole page HTML) (optional)
     * @param  bool $outer_html Return outer HTML of the selected element (false by default, returns inner HTML) (optional)
     * @param  string $proxy Proxy country code, for geotargeting (US by default) (optional)
     * @param  bool $disable_js Disable JS execution (false by default) (optional)
     * @param  bool $inline_css Inline included CSS files to make page viewable on other domains (false by default) (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ScrappedPage
     */
    public function getPage($url, $selector = null, $outer_html = null, $proxy = null, $disable_js = null, $inline_css = null)
    {
        list($response) = $this->getPageWithHttpInfo($url, $selector, $outer_html, $proxy, $disable_js, $inline_css);
        return $response;
    }

    /**
     * Operation getPageWithHttpInfo
     *
     * Get page HTML by URL (renders JS in Chrome and uses rotating proxies)
     *
     * @param  string $url URL of the page to get (required)
     * @param  string $selector CSS selector to get a part of the page (null by default, returns whole page HTML) (optional)
     * @param  bool $outer_html Return outer HTML of the selected element (false by default, returns inner HTML) (optional)
     * @param  string $proxy Proxy country code, for geotargeting (US by default) (optional)
     * @param  bool $disable_js Disable JS execution (false by default) (optional)
     * @param  bool $inline_css Inline included CSS files to make page viewable on other domains (false by default) (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ScrappedPage, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPageWithHttpInfo($url, $selector = null, $outer_html = null, $proxy = null, $disable_js = null, $inline_css = null)
    {
        $request = $this->getPageRequest($url, $selector, $outer_html, $proxy, $disable_js, $inline_css);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\ScrappedPage' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ScrappedPage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\ScrappedPage';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ScrappedPage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getPageAsync
     *
     * Get page HTML by URL (renders JS in Chrome and uses rotating proxies)
     *
     * @param  string $url URL of the page to get (required)
     * @param  string $selector CSS selector to get a part of the page (null by default, returns whole page HTML) (optional)
     * @param  bool $outer_html Return outer HTML of the selected element (false by default, returns inner HTML) (optional)
     * @param  string $proxy Proxy country code, for geotargeting (US by default) (optional)
     * @param  bool $disable_js Disable JS execution (false by default) (optional)
     * @param  bool $inline_css Inline included CSS files to make page viewable on other domains (false by default) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPageAsync($url, $selector = null, $outer_html = null, $proxy = null, $disable_js = null, $inline_css = null)
    {
        return $this->getPageAsyncWithHttpInfo($url, $selector, $outer_html, $proxy, $disable_js, $inline_css)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPageAsyncWithHttpInfo
     *
     * Get page HTML by URL (renders JS in Chrome and uses rotating proxies)
     *
     * @param  string $url URL of the page to get (required)
     * @param  string $selector CSS selector to get a part of the page (null by default, returns whole page HTML) (optional)
     * @param  bool $outer_html Return outer HTML of the selected element (false by default, returns inner HTML) (optional)
     * @param  string $proxy Proxy country code, for geotargeting (US by default) (optional)
     * @param  bool $disable_js Disable JS execution (false by default) (optional)
     * @param  bool $inline_css Inline included CSS files to make page viewable on other domains (false by default) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPageAsyncWithHttpInfo($url, $selector = null, $outer_html = null, $proxy = null, $disable_js = null, $inline_css = null)
    {
        $returnType = '\OpenAPI\Client\Model\ScrappedPage';
        $request = $this->getPageRequest($url, $selector, $outer_html, $proxy, $disable_js, $inline_css);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPage'
     *
     * @param  string $url URL of the page to get (required)
     * @param  string $selector CSS selector to get a part of the page (null by default, returns whole page HTML) (optional)
     * @param  bool $outer_html Return outer HTML of the selected element (false by default, returns inner HTML) (optional)
     * @param  string $proxy Proxy country code, for geotargeting (US by default) (optional)
     * @param  bool $disable_js Disable JS execution (false by default) (optional)
     * @param  bool $inline_css Inline included CSS files to make page viewable on other domains (false by default) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getPageRequest($url, $selector = null, $outer_html = null, $proxy = null, $disable_js = null, $inline_css = null)
    {
        // verify the required parameter 'url' is set
        if ($url === null || (is_array($url) && count($url) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $url when calling getPage'
            );
        }

        $resourcePath = '/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($url !== null) {
            $queryParams['url'] = ObjectSerializer::toQueryValue($url);
        }
        // query params
        if ($selector !== null) {
            $queryParams['selector'] = ObjectSerializer::toQueryValue($selector);
        }
        // query params
        if ($outer_html !== null) {
            $queryParams['outer_html'] = ObjectSerializer::toQueryValue($outer_html);
        }
        // query params
        if ($proxy !== null) {
            $queryParams['proxy'] = ObjectSerializer::toQueryValue($proxy);
        }
        // query params
        if ($disable_js !== null) {
            $queryParams['disable_js'] = ObjectSerializer::toQueryValue($disable_js);
        }
        // query params
        if ($inline_css !== null) {
            $queryParams['inline_css'] = ObjectSerializer::toQueryValue($inline_css);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_key');
        if ($apiKey !== null) {
            $queryParams['api_key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
