<?php
/**
 * HTMLApi
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * WebScraping.AI
 *
 * A client for https://webscraping.ai API. It provides a web scaping automation API with Chrome JS rendering, rotating proxies and builtin HTML parsing.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@webscraping.ai
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\webscraping_ai;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * HTMLApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class HTMLApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index)
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getHTML
     *
     * Page HTML by URL
     *
     * @param  string $url URL of the target page (required)
     * @param  map[string,string] $headers HTTP headers to pass to the target page. Can be specified either via a nested query parameter (...&amp;headers[One]&#x3D;value1&amp;headers&#x3D;[Another]&#x3D;value2) or as a JSON encoded object (...&amp;headers&#x3D;{\&quot;One\&quot;: \&quot;value1\&quot;, \&quot;Another\&quot;: \&quot;value2\&quot;}) (optional)
     * @param  int $timeout Maximum processing time in ms. Increase it in case of timeout errors (5000 by default, maximum is 30000) (optional, default to 5000)
     * @param  bool $js Execute on-page JavaScript using a headless browser (true by default), costs 2 requests (optional, default to true)
     * @param  string $proxy Type of proxy, use residential proxies if your site restricts traffic from datacenters (datacenter by default) (optional, default to 'datacenter')
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function getHTML($url, $headers = null, $timeout = 5000, $js = true, $proxy = 'datacenter')
    {
        $this->getHTMLWithHttpInfo($url, $headers, $timeout, $js, $proxy);
    }

    /**
     * Operation getHTMLWithHttpInfo
     *
     * Page HTML by URL
     *
     * @param  string $url URL of the target page (required)
     * @param  map[string,string] $headers HTTP headers to pass to the target page. Can be specified either via a nested query parameter (...&amp;headers[One]&#x3D;value1&amp;headers&#x3D;[Another]&#x3D;value2) or as a JSON encoded object (...&amp;headers&#x3D;{\&quot;One\&quot;: \&quot;value1\&quot;, \&quot;Another\&quot;: \&quot;value2\&quot;}) (optional)
     * @param  int $timeout Maximum processing time in ms. Increase it in case of timeout errors (5000 by default, maximum is 30000) (optional, default to 5000)
     * @param  bool $js Execute on-page JavaScript using a headless browser (true by default), costs 2 requests (optional, default to true)
     * @param  string $proxy Type of proxy, use residential proxies if your site restricts traffic from datacenters (datacenter by default) (optional, default to 'datacenter')
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function getHTMLWithHttpInfo($url, $headers = null, $timeout = 5000, $js = true, $proxy = 'datacenter')
    {
        $request = $this->getHTMLRequest($url, $headers, $timeout, $js, $proxy);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 402:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\PageError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 504:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getHTMLAsync
     *
     * Page HTML by URL
     *
     * @param  string $url URL of the target page (required)
     * @param  map[string,string] $headers HTTP headers to pass to the target page. Can be specified either via a nested query parameter (...&amp;headers[One]&#x3D;value1&amp;headers&#x3D;[Another]&#x3D;value2) or as a JSON encoded object (...&amp;headers&#x3D;{\&quot;One\&quot;: \&quot;value1\&quot;, \&quot;Another\&quot;: \&quot;value2\&quot;}) (optional)
     * @param  int $timeout Maximum processing time in ms. Increase it in case of timeout errors (5000 by default, maximum is 30000) (optional, default to 5000)
     * @param  bool $js Execute on-page JavaScript using a headless browser (true by default), costs 2 requests (optional, default to true)
     * @param  string $proxy Type of proxy, use residential proxies if your site restricts traffic from datacenters (datacenter by default) (optional, default to 'datacenter')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getHTMLAsync($url, $headers = null, $timeout = 5000, $js = true, $proxy = 'datacenter')
    {
        return $this->getHTMLAsyncWithHttpInfo($url, $headers, $timeout, $js, $proxy)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getHTMLAsyncWithHttpInfo
     *
     * Page HTML by URL
     *
     * @param  string $url URL of the target page (required)
     * @param  map[string,string] $headers HTTP headers to pass to the target page. Can be specified either via a nested query parameter (...&amp;headers[One]&#x3D;value1&amp;headers&#x3D;[Another]&#x3D;value2) or as a JSON encoded object (...&amp;headers&#x3D;{\&quot;One\&quot;: \&quot;value1\&quot;, \&quot;Another\&quot;: \&quot;value2\&quot;}) (optional)
     * @param  int $timeout Maximum processing time in ms. Increase it in case of timeout errors (5000 by default, maximum is 30000) (optional, default to 5000)
     * @param  bool $js Execute on-page JavaScript using a headless browser (true by default), costs 2 requests (optional, default to true)
     * @param  string $proxy Type of proxy, use residential proxies if your site restricts traffic from datacenters (datacenter by default) (optional, default to 'datacenter')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getHTMLAsyncWithHttpInfo($url, $headers = null, $timeout = 5000, $js = true, $proxy = 'datacenter')
    {
        $returnType = '';
        $request = $this->getHTMLRequest($url, $headers, $timeout, $js, $proxy);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getHTML'
     *
     * @param  string $url URL of the target page (required)
     * @param  map[string,string] $headers HTTP headers to pass to the target page. Can be specified either via a nested query parameter (...&amp;headers[One]&#x3D;value1&amp;headers&#x3D;[Another]&#x3D;value2) or as a JSON encoded object (...&amp;headers&#x3D;{\&quot;One\&quot;: \&quot;value1\&quot;, \&quot;Another\&quot;: \&quot;value2\&quot;}) (optional)
     * @param  int $timeout Maximum processing time in ms. Increase it in case of timeout errors (5000 by default, maximum is 30000) (optional, default to 5000)
     * @param  bool $js Execute on-page JavaScript using a headless browser (true by default), costs 2 requests (optional, default to true)
     * @param  string $proxy Type of proxy, use residential proxies if your site restricts traffic from datacenters (datacenter by default) (optional, default to 'datacenter')
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getHTMLRequest($url, $headers = null, $timeout = 5000, $js = true, $proxy = 'datacenter')
    {
        // verify the required parameter 'url' is set
        if ($url === null || (is_array($url) && count($url) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $url when calling getHTML'
            );
        }
        if ($timeout !== null && $timeout > 30000) {
            throw new \InvalidArgumentException('invalid value for "$timeout" when calling HTMLApi.getHTML, must be smaller than or equal to 30000.');
        }
        if ($timeout !== null && $timeout < 1) {
            throw new \InvalidArgumentException('invalid value for "$timeout" when calling HTMLApi.getHTML, must be bigger than or equal to 1.');
        }


        $resourcePath = '/html';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($url !== null) {
            if('form' === 'form' && is_array($url)) {
                foreach($url as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['url'] = $url;
            }
        }
        // query params
        if ($headers !== null) {
            if('form' === 'form' && is_array($headers)) {
                foreach($headers as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['headers'] = $headers;
            }
        }
        // query params
        if ($timeout !== null) {
            if('form' === 'form' && is_array($timeout)) {
                foreach($timeout as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['timeout'] = $timeout;
            }
        }
        // query params
        if ($js !== null) {
            if('form' === 'form' && is_array($js)) {
                foreach($js as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['js'] = $js;
            }
        }
        // query params
        if ($proxy !== null) {
            if('form' === 'form' && is_array($proxy)) {
                foreach($proxy as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['proxy'] = $proxy;
            }
        }



        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/html'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_key');
        if ($apiKey !== null) {
            $queryParams['api_key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postHTML
     *
     * Page HTML by URL with POST request to the target page
     *
     * @param  string $url URL of the target page (required)
     * @param  map[string,string] $headers HTTP headers to pass to the target page. Can be specified either via a nested query parameter (...&amp;headers[One]&#x3D;value1&amp;headers&#x3D;[Another]&#x3D;value2) or as a JSON encoded object (...&amp;headers&#x3D;{\&quot;One\&quot;: \&quot;value1\&quot;, \&quot;Another\&quot;: \&quot;value2\&quot;}) (optional)
     * @param  int $timeout Maximum processing time in ms. Increase it in case of timeout errors (5000 by default, maximum is 30000) (optional, default to 5000)
     * @param  bool $js Execute on-page JavaScript using a headless browser (true by default), costs 2 requests (optional, default to true)
     * @param  string $proxy Type of proxy, use residential proxies if your site restricts traffic from datacenters (datacenter by default) (optional, default to 'datacenter')
     * @param  map[string,object] $request_body Request body to pass to the target page (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function postHTML($url, $headers = null, $timeout = 5000, $js = true, $proxy = 'datacenter', $request_body = null)
    {
        $this->postHTMLWithHttpInfo($url, $headers, $timeout, $js, $proxy, $request_body);
    }

    /**
     * Operation postHTMLWithHttpInfo
     *
     * Page HTML by URL with POST request to the target page
     *
     * @param  string $url URL of the target page (required)
     * @param  map[string,string] $headers HTTP headers to pass to the target page. Can be specified either via a nested query parameter (...&amp;headers[One]&#x3D;value1&amp;headers&#x3D;[Another]&#x3D;value2) or as a JSON encoded object (...&amp;headers&#x3D;{\&quot;One\&quot;: \&quot;value1\&quot;, \&quot;Another\&quot;: \&quot;value2\&quot;}) (optional)
     * @param  int $timeout Maximum processing time in ms. Increase it in case of timeout errors (5000 by default, maximum is 30000) (optional, default to 5000)
     * @param  bool $js Execute on-page JavaScript using a headless browser (true by default), costs 2 requests (optional, default to true)
     * @param  string $proxy Type of proxy, use residential proxies if your site restricts traffic from datacenters (datacenter by default) (optional, default to 'datacenter')
     * @param  map[string,object] $request_body Request body to pass to the target page (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function postHTMLWithHttpInfo($url, $headers = null, $timeout = 5000, $js = true, $proxy = 'datacenter', $request_body = null)
    {
        $request = $this->postHTMLRequest($url, $headers, $timeout, $js, $proxy, $request_body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 402:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\PageError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 504:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation postHTMLAsync
     *
     * Page HTML by URL with POST request to the target page
     *
     * @param  string $url URL of the target page (required)
     * @param  map[string,string] $headers HTTP headers to pass to the target page. Can be specified either via a nested query parameter (...&amp;headers[One]&#x3D;value1&amp;headers&#x3D;[Another]&#x3D;value2) or as a JSON encoded object (...&amp;headers&#x3D;{\&quot;One\&quot;: \&quot;value1\&quot;, \&quot;Another\&quot;: \&quot;value2\&quot;}) (optional)
     * @param  int $timeout Maximum processing time in ms. Increase it in case of timeout errors (5000 by default, maximum is 30000) (optional, default to 5000)
     * @param  bool $js Execute on-page JavaScript using a headless browser (true by default), costs 2 requests (optional, default to true)
     * @param  string $proxy Type of proxy, use residential proxies if your site restricts traffic from datacenters (datacenter by default) (optional, default to 'datacenter')
     * @param  map[string,object] $request_body Request body to pass to the target page (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postHTMLAsync($url, $headers = null, $timeout = 5000, $js = true, $proxy = 'datacenter', $request_body = null)
    {
        return $this->postHTMLAsyncWithHttpInfo($url, $headers, $timeout, $js, $proxy, $request_body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postHTMLAsyncWithHttpInfo
     *
     * Page HTML by URL with POST request to the target page
     *
     * @param  string $url URL of the target page (required)
     * @param  map[string,string] $headers HTTP headers to pass to the target page. Can be specified either via a nested query parameter (...&amp;headers[One]&#x3D;value1&amp;headers&#x3D;[Another]&#x3D;value2) or as a JSON encoded object (...&amp;headers&#x3D;{\&quot;One\&quot;: \&quot;value1\&quot;, \&quot;Another\&quot;: \&quot;value2\&quot;}) (optional)
     * @param  int $timeout Maximum processing time in ms. Increase it in case of timeout errors (5000 by default, maximum is 30000) (optional, default to 5000)
     * @param  bool $js Execute on-page JavaScript using a headless browser (true by default), costs 2 requests (optional, default to true)
     * @param  string $proxy Type of proxy, use residential proxies if your site restricts traffic from datacenters (datacenter by default) (optional, default to 'datacenter')
     * @param  map[string,object] $request_body Request body to pass to the target page (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postHTMLAsyncWithHttpInfo($url, $headers = null, $timeout = 5000, $js = true, $proxy = 'datacenter', $request_body = null)
    {
        $returnType = '';
        $request = $this->postHTMLRequest($url, $headers, $timeout, $js, $proxy, $request_body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postHTML'
     *
     * @param  string $url URL of the target page (required)
     * @param  map[string,string] $headers HTTP headers to pass to the target page. Can be specified either via a nested query parameter (...&amp;headers[One]&#x3D;value1&amp;headers&#x3D;[Another]&#x3D;value2) or as a JSON encoded object (...&amp;headers&#x3D;{\&quot;One\&quot;: \&quot;value1\&quot;, \&quot;Another\&quot;: \&quot;value2\&quot;}) (optional)
     * @param  int $timeout Maximum processing time in ms. Increase it in case of timeout errors (5000 by default, maximum is 30000) (optional, default to 5000)
     * @param  bool $js Execute on-page JavaScript using a headless browser (true by default), costs 2 requests (optional, default to true)
     * @param  string $proxy Type of proxy, use residential proxies if your site restricts traffic from datacenters (datacenter by default) (optional, default to 'datacenter')
     * @param  map[string,object] $request_body Request body to pass to the target page (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function postHTMLRequest($url, $headers = null, $timeout = 5000, $js = true, $proxy = 'datacenter', $request_body = null)
    {
        // verify the required parameter 'url' is set
        if ($url === null || (is_array($url) && count($url) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $url when calling postHTML'
            );
        }
        if ($timeout !== null && $timeout > 30000) {
            throw new \InvalidArgumentException('invalid value for "$timeout" when calling HTMLApi.postHTML, must be smaller than or equal to 30000.');
        }
        if ($timeout !== null && $timeout < 1) {
            throw new \InvalidArgumentException('invalid value for "$timeout" when calling HTMLApi.postHTML, must be bigger than or equal to 1.');
        }


        $resourcePath = '/html';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($url !== null) {
            if('form' === 'form' && is_array($url)) {
                foreach($url as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['url'] = $url;
            }
        }
        // query params
        if ($headers !== null) {
            if('form' === 'form' && is_array($headers)) {
                foreach($headers as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['headers'] = $headers;
            }
        }
        // query params
        if ($timeout !== null) {
            if('form' === 'form' && is_array($timeout)) {
                foreach($timeout as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['timeout'] = $timeout;
            }
        }
        // query params
        if ($js !== null) {
            if('form' === 'form' && is_array($js)) {
                foreach($js as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['js'] = $js;
            }
        }
        // query params
        if ($proxy !== null) {
            if('form' === 'form' && is_array($proxy)) {
                foreach($proxy as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['proxy'] = $proxy;
            }
        }



        // body params
        $_tempBody = null;
        if (isset($request_body)) {
            $_tempBody = $request_body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/html']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/html'],
                ['application/json', 'application/x-www-form-urlencoded', 'application/xml', 'text/plain']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_key');
        if ($apiKey !== null) {
            $queryParams['api_key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
