<?php
/**
 * SelectedHTMLApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * WebScraping.AI
 *
 * A client for https://webscraping.ai API. It provides a web scaping automation API with Chrome JS rendering, rotating proxies and builtin HTML parsing.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@webscraping.ai
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SelectedHTMLApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SelectedHTMLApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getSelected
     *
     * HTML of a selected page area by URL and CSS selector.
     *
     */
    public function testGetSelected()
    {
    }

    /**
     * Test case for getSelectedMultiple
     *
     * HTML of multiple page areas by URL and CSS selectors.
     *
     */
    public function testGetSelectedMultiple()
    {
    }

    /**
     * Test case for postSelected
     *
     * HTML of a selected page areas by URL and CSS selector, with POST request to the target page.
     *
     */
    public function testPostSelected()
    {
    }

    /**
     * Test case for postSelectedMultiple
     *
     * HTML of multiple page areas by URL and CSS selectors, with POST request to the target page.
     *
     */
    public function testPostSelectedMultiple()
    {
    }
}
